// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAy6uEeiFHyxfgrk25Sa-_Bf4nJlKdmYKg',
    appId: '1:749503286075:web:dfce0cdcafd446f2d9851e',
    messagingSenderId: '749503286075',
    projectId: 'to-done-flutter',
    authDomain: 'to-done-flutter.firebaseapp.com',
    storageBucket: 'to-done-flutter.appspot.com',
    measurementId: 'G-03XMDZLTL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_aklW0vwt6shCAmmpRg5RXC5VE27YfyM',
    appId: '1:749503286075:android:bef5e5f695ae365dd9851e',
    messagingSenderId: '749503286075',
    projectId: 'to-done-flutter',
    storageBucket: 'to-done-flutter.appspot.com',
  );
}
